### ISSUE TITLE
Not supported in the latest versions.

### ISSUE THREAD

**Issue by PoornaSenadheera100** [PoornaSenadheera100/Recycler-View-Android#15]
Recycler view is not supported in the latest version (build tool version 33.0.0).

**Comment by IT21138386** [comment]
Please try replacing the existing recycleview dependency in the **build.gradle** file with the code segment below

`implementation "androidx.recyclerview:recyclerview:1.1.0"
// For control over item selection of both touch and mouse driven selection
implementation "androidx.recyclerview:recyclerview-selection:1.2.0-alpha01"`

**Comment by Sathira-Wijeratne** [comment]
Please try replacing the existing recycleview dependency in the **build.gradle** file with the code segment below

`implementation "androidx.recyclerview:recyclerview:1.1.0"`
`// For control over item selection of both touch and mouse driven selection`
`implementation "androidx.recyclerview:recyclerview-selection:1.2.0-alpha01"`

**Comment by PoornaSenadheera100** [comment]
Good solution. The Error was resolved. Thank you @Sathira-Wijeratne
